;; Copyright (c) 2014, Ömercan Yazici <pearcoding AT gmail.com>
;; All rights reserved.
;;
;; Redistribution and use in source and binary forms, with or without modification,
;; are permitted provided that the following conditions are met:
;;
;;    1. Redistributions of source code must retain the above copyright notice,
;;       this list of conditions and the following disclaimer.
;;
;;    2. Redistributions in binary form must reproduce the above copyright
;;       notice, this list of conditions and the following disclaimer in the
;;       documentation and/or other materials provided with the distribution.
;;
;;    3. Neither the name of the copyright owner may be used
;;       to endorse or promote products derived from this software without
;;       specific prior written permission.
;;
;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
;; ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
;; WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
;; DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER BE LIABLE FOR
;; ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
;; (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
;; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
;; ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
;; (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE

;; File from TheGreatJourney < http://www.pearcoding.eu/projects/thegreatjourney >
(environment
	;; Development 1 Day == 1min => 0.041666667
	;; Deploy 1 Day == 20min => 0.833333333
	:steps				0.041666667
		
	:hourCycleTime		60;; minutes
	:dayCycleTime		24;; hours
	:monthCycleTime		14;; days
	:yearCycleTime		4;; months
	
	:sunPower			[
		(point
			:time		0
			:value		0
		),
		(point
			:time		0.25;; 6/24
			:value		0.25
		),
		(point
			:time		0.5
			:value		1
		),
		(point
			:time		0.83;; 18/24
			:value		0.25
		),
		(point
			:time		1
			:value		0
		)
	]
	
	:sunColor			[
		(point
			:time		0
			:value		[0.3, 0.3, 1]
		),
		(point
			:time		0.25;; 6/24
			:value		[0.8, 0.2, 0.4]
		),
		(point
			:time		0.5
			:value		[1, 1, 1]
		),
		(point
			:time		0.83;; 18/24
			:value		[1, 1, 1]
		),
		(point
			:time		1
			:value		[0.3, 0.3, 1]
		)
	]
	
	:sunDirection		[
		(point
			:time		0
			:value		[0.5, -0.5]
		),
		(point
			:time		0.25;; 6/24
			:value		[0, 0]
		),
		(point
			:time		0.5
			:value		[0.5, 0.5]
		),
		(point
			:time		0.83;; 18/24
			:value		[1, 0]
		),
		(point
			:time		1
			:value		[0.5, -0.5]
		)
	]
)
